easy_admin:
    site_name: ECTRL administration
    formats:
            date:     'd/m/Y'
            time:     'H:i'
            datetime: 'd/m/Y'
    design:
        brand_color: '#58c0c1'
        assets:
            favicon: '/favicon/favicon-32x32.png'
            js: ['/js/codeGenerator.js']
        menu:
           - { label: Gestion Clients }
           - { entity: Company, icon: industry }
           - { entity: RegisterCode, icon: barcode }
           - { entity: Role, icon: users }
           - { entity: User, icon: address-card }
           - { label: Gestion des modèles d'audits }
           - { entity: Certification, icon: list-alt }
           - { entity: Theme, icon: list-ol }
           - { entity: Requirement, icon: check-square }
    list:
        actions: ['show']




    entities:
        Company:
            class: App\Entity\Company

            label: Sociétés
            icon: tasks
            list:
                title: Sociétés
                max_results: 100
                actions:
                    - { name: new, label: Créer une société }
                fields:
                    - { property: name, label: Nom }
                    - { property: certifications, label: Modèle d'audit }
                    - { property: registerCodes, label: Code d'enregistrement}
                    - { property: users, label: Utilisateurs }
                    - { property: maxCertificationsNb, label: Limite de modèles }
                    - { property: creationDate, label: Date de création}
            show:
                title: Sociétés
                max_results: 100
                fields:
                    - { property: name, label: Nom }
                    - { property: certifications, label: Modèle d'audit }
                    - { property: registerCodes, label: Code d'enregistrement}
                    - { property: users, label: Utilisateurs }
                    - { property: maxCertificationsNb, label: Limite de modèles }
                    - { property: creationDate, label: Date de création}
            new:
                title: Créer une société
                fields:
                    - { property: name, label: Nom }
                    - { property: maxCertificationsNb, label: Limite de modèles, help: Laisser vide pour rendre illimiter le nombre de modèle disponible  }
# easyadmin bug who don't save one tot many relation  - { property: certifications, label: Modèle d'audit }
            edit:
                title: Modifier cette société
                fields:
                    - { property: name, label: Nom }
                    - { property: maxCertificationsNb, label: Limite de modèles, help: Laisser vide pour rendre illimiter le nombre de modèle disponible }
# easyadmin bug who don't save one tot many relation   - { property: certifications }
                    - { property: registerCodes, label: Code d'enregistrement}

        RegisterCode:
            class: App\Entity\RegisterCode
            label: Codes d'enregistrement
            list:
                title: Codes d'enregistrement
                max_results: 100
                actions:
                    - { name: new, label: Créer un code d'enregistrement }
                fields:
                    - { property: codeContent, label: Code d'enregistrement }
                    - { property: company, label: Société }
                    - { property: role, label: Role }
                    - { property: maxNbOfUsers, label: Nb max d'utilisateur }
                    - { property: creationDate, label: Date de création }
            show:
                title: Codes d'enregistrement
                max_results: 100
                fields:
                    - { property: codeContent, label: Code d'enregistrement }
                    - { property: company, label: Société }
                    - { property: role, label: Role }
                    - { property: maxNbOfUsers, label: Nb max d'utilisateur }
                    - { property: creationDate, label: Date de création }
            new:
                title: Créer un code d'enregistrement
                fields:
                    - { property: codeContent, label: Code d'enregistrement, css_class: code-generator }
                    - { property: company, label: Société }
                    - { property: role, label: Role }
                    - { property: maxNbOfUsers, label: Nombre maximum d'utilisateur }
            edit:
                title: Modifier le code d'enregistrement
                fields:
                    - { property: codeContent, label: Code d'enregistrement }
                    - { property: company, label: Société }
                    - { property: role, label: Role }
                    - { property: maxNbOfUsers, label: Nombre maximum d'utilisateur }

        Role:
            class: App\Entity\Role
            label: Rôles
            help: La hiérarchie des rôles va de 3 pour les assistants qualité à 1 pour le directeur.
            list:
                title: Rôles
                actions:
                    - { name: new, label: Créer un rôle }
                fields:
                    - { property: title, label: Titre }
                    - { property: description, label: Description }
                    - { property: rank, label: Niveau hiérarchique }
                    - { property: registerCodes, label: Code d'enregistrement }
                    - { property: users, label: utilisateurs }
                    - { property: creationDate, label: Date de création }
            show:
                title: Rôles
                fields:
                    - { property: title, label: Titre }
                    - { property: rank, label: Niveau hiérarchique }
                    - { property: registerCodes, label: Code d'enregistrement }
                    - { property: users, label: utilisateurs }
                    - { property: creationDate, label: Date de création }
            new:
                title: Créer un rôle
                fields:
                    - { property: title, label: Titre }
                    - { property: description, label: Description }
                    - { property: rank, label: Niveau hiérarchique }
            edit:
                title: Modifier un rôle
                fields:
                    - { property: title, label: Titre }
                    - { property: description, label: Description }
                    - { property: rank, label: Niveau hiérarchique }
                    - { property: users, label: utilisateurs }

        User:
            class: App\Entity\User
            label: Utilisateurs
            disabled_actions: [new]
            list:
                title: utilisateurs
                max_results: 100
                fields:
                    - { property: email, label: Email }
                    - { property: firstName, label: Prénom }
                    - { property: lastName, label: Nom }
                    - { property: userEnable, label: Utilisateur activé }
                    - { property: company, label: Société }
                    - { property: role, label: Rôle }
                    - { property: isBanned, label: Utilisateur banni }
                    - { property: registerCode, label: Code d'enregistrement }
                    - { property: creationDate, label: Date de création }
            show:
                title: Utilisateur
                max_results: 100
                fields:
                    - { property: email, label: Email }
                    - { property: firstName, label: Prénom }
                    - { property: lastName, label: Nom }
                    - { property: userEnable, label: Utilisateur activé }
                    - { property: company, label: Société }
                    - { property: role, label: Rôle }
                    - { property: isBanned, label: Utilisateur banni }
                    - { property: registerCode, label: Code d'enregistrement }
                    - { property: creationDate, label: Date de création }
            edit:
                title: Modifier le code d'enregistrement
                fields:
                    - { property: email, label: Email }
                    - { property: firstName, label: Prénom }
                    - { property: lastName, label: Nom }
                    - { property: userEnable, label: Utilisateur activé }
                    - { property: isBanned, label: Utilisateur banni }



        Certification:
            class: App\Entity\Certification
            label: Modèles d'audits
            list:
                title: Modèles d'audits
                max_results: 100
                actions:
                    - { name: new, label: Créer un modèle }
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: themes, label: Thèmes }
                    - { property: requirements, label: Exigences }
                    - { property: companies, label: Sociétés }
                    - { property: audits, label: Nb d'Audits }
                    - { property: creationDate, label: Date de création}
            show:
                title: Modèle d'audit
                max_results: 100
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: themes, label: Thèmes }
                    - { property: requirements, label: Exigences }
                    - { property: companies, label: Sociétés }
                    - { property: creationDate, label: Date de création}
            new:
                title: Créer un modèle d'audit
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: companies, label: Sociétés }
            edit:
                title: Modifier un modèle d'audit
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: companies, label: Sociétés }

        Theme:
            class: App\Entity\Theme
            label: Themes
            list:
                title: Themes des modèles d'audits
                max_results: 100
                actions:
                    - { name: new, label: Créer un thème }
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
                    - { property: rankCertification, label: Position dans modèle }
                    - { property: requirements, label: Exigences de ce thème }
                    - { property: creationDate, label: Date de création}
            show:
                title: Theme d'un audit
                max_results: 100
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
                    - { property: rankCertification, label: Position dans modèle }
                    - { property: color, label: Couleur }
                    - { property: creationDate, label: Date de création}
            new:
                title: Créer un thème
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
                    - { property: rankCertification, label: Position dans modèle }
                    - { property: color, label: Couleur, help: La couleur de thème doit être au format hexadécimal }
            edit:
                title: Modifier un thème
                fields:
                    - { property: title, label: Intitulé }
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
                    - { property: rankCertification, label: Position dans modèle }
                    - { property: color, label: Couleur, help: La couleur de thème doit être au format hexadécimal }

        Requirement:
            class: App\Entity\Requirement
            label: Exigences
            list:
                title: Exigences des modèles d'audits
                max_results: 100
                actions:
                    - { name: new, label: Créer une exigence }
                fields:
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
#                    - { property: rankCertification, label: Position dans modèle }
                    - { property: theme, label: Appartient au thème }
                    - { property: rankTheme, label: Position dans thème }
                    - { property: creationDate, label: Date de création}
            show:
                title: Exigence d'un modèle
                max_results: 100
                fields:
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
 #                   - { property: rankCertification, label: Position dans modèle }
                    - { property: theme, label: Appartient au thème }
                    - { property: rankTheme, label: Position dans thème }
                    - { property: creationDate, label: Date de création}
            new:
                title: Créer une exigence
                fields:
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
#                    - { property: rankCertification, label: Position dans modèle }
                    - { property: theme, label: Appartient au thème }
                    - { property: rankTheme, label: Position dans thème }
            edit:
                title: Modifier une exigence
                fields:
                    - { property: description, label: Description }
                    - { property: certification, label: Appartient au modèle }
#                    - { property: rankCertification, label: Position dans modèle }
                    - { property: theme, label: Appartient au thème }
                    - { property: rankTheme, label: Position dans thème }