swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }

#Use for dev. remove and set env variable for prod
    transport:        gmail
    username:         ectrl.service@gmail.com
    password:         29drtx79
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false